enableGlobalCache: false

enableImmutableInstalls: false

logFilters:
  - code: YN0060
    level: discard
  - code: YN0002
    level: discard
  - code: YN0086
    level: discard

nodeLinker: node-modules

npmScopes:
  echoes-of-order:
    npmAuthToken: "${NPM_AUTH_TOKEN:-}"
    npmPublishRegistry: "https://npm.pkg.github.com/"
    npmRegistryServer: "https://npm.pkg.github.com/"
